### ISSUE TITLE
Design landing page

### ISSUE THREAD

**Issue by HuxleyBerry** [codersforcauses/bluecrew#37]
The client has asked for a simple landing page. They specifically mentioned the duolingo landing page as something they liked. That looks like this (https://www.duolingo.com/):

![image](https://github.com/user-attachments/assets/820faa25-9829-4479-8c25-9dae49ad1f08)

This issue is to design a similar page for the bluecrew bingo game.

**Comment by survivzhang** [comment]
<img width="856" alt="Screenshot 2024-12-14 at 1 22 16 PM" src="https://github.com/user-attachments/assets/c4b00121-e7ca-40dd-81c4-5b8d4fac3855" />

**Comment by survivzhang** [comment]
<img width="881" alt="Screenshot 2024-12-14 at 1 29 06 PM" src="https://github.com/user-attachments/assets/acb41abb-ef02-4562-82c0-cbc48e1c1697" />

**Comment by HuxleyBerry** [comment]
Nice!
