### ISSUE TITLE
Create Registration Modal

### ISSUE THREAD

**Issue by HuxleyBerry** [codersforcauses/bluecrew#6]
The modal should include the following fields:
- Username
- First Name (optional)
- Last Name (optional)
- Email
- Password
- Confirm Password

The modal should also contain button to register.

I suggest using this vuetify component: https://vuetifyjs.com/en/components/dialogs

**Comment by lainos123** [comment]
![Screenshot 2024-12-13 at 10 46 35 PM](https://github.com/user-attachments/assets/a2f59c73-8413-43a1-99e7-bcd97ec6a5c6)
Current Progress
